name: school_sync
description: Automation school management app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  clock: ^1.1.1
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.2
  drift: ^2.10.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  intl: ^0.18.1
  logging: ^1.2.0
  meta: ^1.9.1
  package_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.0.15
  platform: ^3.1.0
  registry:
    git: https://github.com/jogboms/registry.dart.git
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  sqlite3_flutter_libs: ^0.5.15
  tabler_icons: ^2.5.0+1
  universal_io: ^2.2.2
  url_launcher: ^6.1.12
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.10.0
  flutter_test:
    sdk: flutter
  mfsao:
    git:
      url: https://github.com/Mujhtech/mfsao.git
      ref: 1c66ecf3eae246a0fee79f37dfe7cb43b2fb338b
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
